name: 🎨 Run Linters

on: [push]

jobs:

  clang-format:
    if: "!contains(github.event.head_commit.message, '🎨')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: DoozyX/clang-format-lint-action@v0.13
      name: "🎨 Run clang-format"
      with:
        source: '.'
        extensions: 'hpp,cpp'
        clangFormatVersion: 11
        inplace: True
    - uses: EndBug/add-and-commit@v8.0.1
      name: "Commit clang-format Change"
      with:
        author_name: Clang Robot
        author_email: robot@clang-format.com
        message: '🎨 Run clang-format'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
