name: CI

on: [push, pull_request]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        build_type: ['Release', 'Debug']
    steps:
      - uses: actions/checkout@v3

      - uses: lukka/get-cmake@latest

      - name: Configure
        run: |
          mkdir -p build
          cmake -DRECYCLER_ENABLE_TESTS=ON -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" -B build -S .

      - name: Build Tests
        run: |
          cmake --build build --target "Recycler_Tests" --config "${{ matrix.build_type }}" -j
          cmake --build build --target "Recycler_CircularBenchmark" --config "${{ matrix.build_type }}" -j

      - name: Run unit tests
        run: cd build && ctest --build-config "${{ matrix.build_type }}" --progress --verbose

  qemu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_build_sha: ['29c05d13']
        build_arch: [arm64, ppc64le, s390x]
        build_type: ['Release', 'Debug']
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: 💎 Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      -
        name: 🔧 Prepare
        id: prep
        run: |
          # Set output parameters.
          export DOCKER_TAG="reivilo1234/cxx-cmake:${{ matrix.docker_build_sha }}-${{ matrix.build_arch }}"
          echo ::set-output name=tags::${DOCKER_TAG}
      -
        name: 🔧 Configure Recycler
        run: |
          cmake -E make_directory build
          docker run --rm -v $(pwd):/src/ ${{ steps.prep.outputs.tags }} \
            cmake \
            -DRECYCLER_ENABLE_TESTS=ON \
            -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}" \
            -B /src/build/ -S /src
      -
        name: 🔨 Build Tests
        run: |
          docker run --rm -v $(pwd):/src/ ${{ steps.prep.outputs.tags }} \
            cmake --build /src/build --target "Recycler_Tests" --config "${{ matrix.build_type }}" -j
          docker run --rm -v $(pwd):/src/ ${{ steps.prep.outputs.tags }} \
            cmake --build /src/build --target "Recycler_CircularBenchmark" --config "${{ matrix.build_type }}" -j
      -
        name: ✅ Run Tests
        run: |
          docker run --rm -v $(pwd):/src/ ${{ steps.prep.outputs.tags }} \
            /bin/bash -c "cd /src/build && ctest --build-config "${{ matrix.build_type }}" --progress --verbose"
