name: CI

on: [push, pull_request]

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: lukka/get-cmake@latest

      - name: Configure
        run: |
          mkdir -p build
          cmake -DRECYCLER_ENABLE_TESTS=ON -DCMAKE_BUILD_TYPE="Release" -B build -S .

      - name: Build Tests
        run: |
          cmake --build build --target "Recycler_Tests" --config "Release" -j
          cmake --build build --target "Recycler_CircularBenchmark" --config "Release" -j

      - name: Run unit tests
        run: cd build && ctest --build-config "Release" --progress --verbose